nodeLinker: pnp

npmPublishRegistry: "https://registry.npmjs.org"

npmRegistries:
  "https://registry.npmjs.org":
    npmAuthToken: "${NODE_AUTH_TOKEN:-}"

npmRegistryServer: "https://registry.npmjs.org"
